### PR TITLE
Fix format type in cmd_parser_test.

### PR DESCRIPTION
**Pull request by flaviojs**
The stable version was fixed in d440d47c1ae31bd7b28fd2dbe816872ef0f07ea4

### CODE REVIEW

**Comment by flaviojs** [comment]
Question: if CodeQL produces a list of bugs, where can I see it?

**Comment by grossmj** [comment]
> Question: if CodeQL produces a list of bugs, where can I see it?

Not sure that CodeQL produces a list of bugs, from what I understand, it only creates an alert if something wrong is detected. Scanning details can be accessed on https://github.com/GNS3/dynamips/security/code-scanning/tools/CodeQL/status/ however I think it is not public.

**Comment by flaviojs** [comment]
It shows a 404 for me so it's not public.

**Comment by grossmj** [comment]
Do you have access to https://scan.coverity.com/projects/dynamips/view_defects ?

I sent you an invite a while ago however you have not accepted it yet.

**Comment by flaviojs** [comment]
Yes, I am using that list to produce the PRs.
I already have access to the project page and don't see anything to "accept" the invite, not sure what is going on...

**Comment by grossmj** [comment]
> I already have access to the project page and don't see anything to "accept" the invite, not sure what is going on...

Well, I guess this is fine then since you have access to the list.

**Pull request merged**
